prepare first test boot

diff --git a/rc/sv.d/timezone.in b/rc/sv.d/timezone.in
--- a/rc/sv.d/timezone.in
+++ b/rc/sv.d/timezone.in
@@ -2,24 +2,49 @@
 
 # sourcing our current rc.conf requires this to be a bash script
 . @RCDIR@/rc.conf
-. @RCDIR@/functions
+. @RCLIBDIR@/functions
 
 case "$1" in
-	start)
-		stat_busy "Setting timezone"
-		set_timezone "$TIMEZONE"
-		add_daemon timezone
-		stat_done
-		;;
-	stop)
-		stat_busy "Setting timezone"
-		set_timezone "$TIMEZONE"
-		rm_daemon timezone
-		stat_done
-		;;
-	*)
-		echo "usage: $0 {start|stop}"
-		exit 1
-esac
+    start)
+        stat_busy "Setting timezone"
+        zonefile=/usr/share/zoneinfo/$TIMEZONE
 
-# vim: set ts=2 noet:
+        [[ $TIMEZONE ]] || return 1
+
+        if [[ ! -e $zonefile ]]; then
+            printf "error: \`%s' is not a valid time zone\n" "$TIMEZONE"
+            return 1
+        fi
+
+        if [[ -L /etc/localtime && /etc/localtime -ef $zonefile ]]; then
+            return 0
+        else
+            ln -sf "/usr/share/zoneinfo/$TIMEZONE" /etc/localtime
+        fi
+        add_daemon timezone
+        stat_done
+        ;;
+    stop)
+        stat_busy "Setting timezone"
+        zonefile=/usr/share/zoneinfo/$TIMEZONE
+
+        [[ $TIMEZONE ]] || return 1
+
+        if [[ ! -e $zonefile ]]; then
+            printf "error: \`%s' is not a valid time zone\n" "$TIMEZONE"
+            return 1
+        fi
+
+        if [[ -L /etc/localtime && /etc/localtime -ef $zonefile ]]; then
+            return 0
+        else
+            ln -sf "/usr/share/zoneinfo/$TIMEZONE" /etc/localtime
+        fi
+        rm_daemon timezone
+        stat_done
+        ;;
+    *)
+        echo "usage: $0 {start|stop}"
+        exit 1
+        ;;
+esac
